# -*- coding: utf-8 -*-
"""PYSPARK ETL PIPELINE — NYC TAXI DATA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_MakHFSYM0FNkpi1LLe_hPk3GiVf-8F
"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import *
import time
import os
import json
from datetime import datetime

spark = SparkSession.builder \
    .master("local[*]") \
    .appName("NYC_Taxi_ETL") \
    .getOrCreate()

spark.sparkContext.setLogLevel("WARN")
print(f"Spark version: {spark.version}")
print(f"ETL Pipeline started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

print("\n" + "=" * 70)
print("PHASE 2: EXTRACT — Reading Raw Parquet Files")
print("=" * 70)

# Check if files exist from Project 16
files = [
    "yellow_tripdata_2024-01.parquet",
    "yellow_tripdata_2024-02.parquet",
    "yellow_tripdata_2024-03.parquet"
]

# Download if not present (in case you're in a fresh Colab)
import urllib.request
base_url = "https://d37ci6vzurychx.cloudfront.net/trip-data/"
for f in files:
    if not os.path.exists(f):
        print(f"Downloading {f}...")
        urllib.request.urlretrieve(base_url + f, f)

# Read all 3 months
raw_df = spark.read.parquet(*files)

# Log extraction
raw_count = raw_df.count()
raw_columns = len(raw_df.columns)
print(f"\nEXTRACTION COMPLETE:")
print(f"  Files read: {len(files)}")
print(f"  Total rows: {raw_count:,}")
print(f"  Columns: {raw_columns}")
print(f"\nRaw schema:")
raw_df.printSchema()

# Show sample of raw data (before any cleaning)
print("Sample RAW data (notice the mess):")
raw_df.show(5, truncate=False)

print("\n" + "=" * 70)
print("PHASE 3: DATA QUALITY AUDIT — What's Wrong With the Raw Data?")
print("=" * 70)

# ---- STEP 3.1: Null counts ----
print("\nNULL VALUES PER COLUMN:")
null_counts = []
for col_name in raw_df.columns:
    nc = raw_df.filter(F.col(col_name).isNull()).count()
    pct = nc / raw_count * 100
    null_counts.append((col_name, nc, pct))
    if nc > 0:
        print(f"  {col_name:30s}: {nc:>10,} nulls ({pct:.2f}%)")

total_nulls = sum(nc for _, nc, _ in null_counts)
print(f"\n  Total null cells: {total_nulls:,}")

# ---- STEP 3.2: Invalid values ----
print("\nINVALID VALUES:")

negative_fares = raw_df.filter(F.col('fare_amount') < 0).count()
print(f"  Negative fares:        {negative_fares:,}")

zero_fares = raw_df.filter(F.col('fare_amount') == 0).count()
print(f"  Zero fares:            {zero_fares:,}")

negative_tips = raw_df.filter(F.col('tip_amount') < 0).count()
print(f"  Negative tips:         {negative_tips:,}")

zero_distance = raw_df.filter(F.col('trip_distance') == 0).count()
print(f"  Zero-distance trips:   {zero_distance:,}")

negative_total = raw_df.filter(F.col('total_amount') <= 0).count()
print(f"  Non-positive totals:   {negative_total:,}")

huge_fares = raw_df.filter(F.col('fare_amount') > 500).count()
print(f"  Fares > $500:          {huge_fares:,}")

zero_passengers = raw_df.filter(
    (F.col('passenger_count') == 0) | (F.col('passenger_count').isNull())
).count()
print(f"  Zero/null passengers:  {zero_passengers:,}")

# ---- STEP 3.3: Date range check ----
print("\nDATE RANGE CHECK:")
date_stats = raw_df.select(
    F.min('tpep_pickup_datetime').alias('earliest_pickup'),
    F.max('tpep_pickup_datetime').alias('latest_pickup'),
    F.min('tpep_dropoff_datetime').alias('earliest_dropoff'),
    F.max('tpep_dropoff_datetime').alias('latest_dropoff')
)
date_stats.show(truncate=False)

wrong_year = raw_df.filter(F.year('tpep_pickup_datetime') != 2024).count()
print(f"  Trips outside 2024:    {wrong_year:,}")

# ---- STEP 3.4: Value distribution check ----
print("\nVENDOR DISTRIBUTION:")
raw_df.groupBy('VendorID').agg(F.count('*').alias('trips')).orderBy('VendorID').show()

print("PAYMENT TYPE DISTRIBUTION:")
raw_df.groupBy('payment_type').agg(F.count('*').alias('trips')).orderBy('payment_type').show()

print("RATE CODE DISTRIBUTION:")
raw_df.groupBy('RatecodeID').agg(F.count('*').alias('trips')).orderBy('RatecodeID').show()

# QUALITY AUDIT SUMMARY
total_issues = negative_fares + zero_distance + negative_total + wrong_year + zero_passengers
print(f"\nQUALITY AUDIT SUMMARY:")
print(f"  Total rows:           {raw_count:,}")
print(f"  Rows with issues:     {total_issues:,} ({total_issues/raw_count*100:.1f}%)")
print(f"  Clean rows (approx):  {raw_count - total_issues:,}")

print("\n" + "=" * 70)
print("PHASE 4: TRANSFORM — Cleaning & Enrichment")
print("=" * 70)

# ---- STEP 4.1: Remove invalid records ----
print("STEP 4.1: Removing invalid records...")

clean_df = raw_df.filter(
    (F.col('fare_amount') > 0) &
    (F.col('fare_amount') < 500) &
    (F.col('trip_distance') > 0) &
    (F.col('trip_distance') < 200) &
    (F.col('total_amount') > 0) &
    (F.col('total_amount') < 500) &
    (F.col('passenger_count') > 0) &
    (F.col('passenger_count') <= 6) &
    (F.year('tpep_pickup_datetime') == 2024) &
    (F.col('tpep_pickup_datetime') < F.col('tpep_dropoff_datetime'))  # pickup before dropoff
)

clean_count = clean_df.count()
removed = raw_count - clean_count
print(f"  Before: {raw_count:,}")
print(f"  After:  {clean_count:,}")
print(f"  Removed: {removed:,} ({removed/raw_count*100:.1f}%)")


# ---- STEP 4.2: Add computed columns (feature engineering) ----
print("\nSTEP 4.2: Adding computed columns...")

enriched_df = clean_df \
    .withColumn('trip_duration_min',
        F.round((F.unix_timestamp('tpep_dropoff_datetime') -
                 F.unix_timestamp('tpep_pickup_datetime')) / 60, 1)) \
    .withColumn('speed_mph',
        F.when(
            (F.unix_timestamp('tpep_dropoff_datetime') - F.unix_timestamp('tpep_pickup_datetime')) > 60,
            F.round(F.col('trip_distance') /
                    ((F.unix_timestamp('tpep_dropoff_datetime') -
                      F.unix_timestamp('tpep_pickup_datetime')) / 3600), 1)
        ).otherwise(None)) \
    .withColumn('tip_pct',
        F.when(F.col('fare_amount') > 0,
               F.round(F.col('tip_amount') / F.col('fare_amount') * 100, 1))
        .otherwise(0)) \
    .withColumn('cost_per_mile',
        F.when(F.col('trip_distance') > 0,
               F.round(F.col('fare_amount') / F.col('trip_distance'), 2))
        .otherwise(None)) \
    .withColumn('pickup_hour', F.hour('tpep_pickup_datetime')) \
    .withColumn('pickup_date', F.to_date('tpep_pickup_datetime')) \
    .withColumn('pickup_month', F.month('tpep_pickup_datetime')) \
    .withColumn('pickup_day_of_week', F.dayofweek('tpep_pickup_datetime')) \
    .withColumn('day_name',
        F.when(F.col('pickup_day_of_week') == 1, 'Sun')
         .when(F.col('pickup_day_of_week') == 2, 'Mon')
         .when(F.col('pickup_day_of_week') == 3, 'Tue')
         .when(F.col('pickup_day_of_week') == 4, 'Wed')
         .when(F.col('pickup_day_of_week') == 5, 'Thu')
         .when(F.col('pickup_day_of_week') == 6, 'Fri')
         .otherwise('Sat')) \
    .withColumn('time_of_day',
        F.when(F.col('pickup_hour').between(6, 11), 'Morning')
         .when(F.col('pickup_hour').between(12, 16), 'Afternoon')
         .when(F.col('pickup_hour').between(17, 21), 'Evening')
         .otherwise('Night')) \
    .withColumn('is_rush_hour',
        F.when(F.col('pickup_hour').between(7, 9) |
               F.col('pickup_hour').between(17, 19), True)
        .otherwise(False)) \
    .withColumn('is_airport',
        F.when((F.col('PULocationID').isin(132, 138)) |
               (F.col('DOLocationID').isin(132, 138)), True)
        .otherwise(False)) \
    .withColumn('payment_name',
        F.when(F.col('payment_type') == 1, 'Credit Card')
         .when(F.col('payment_type') == 2, 'Cash')
         .when(F.col('payment_type') == 3, 'No Charge')
         .when(F.col('payment_type') == 4, 'Dispute')
         .otherwise('Other')) \
    .withColumn('fare_bucket',
        F.when(F.col('fare_amount') < 10, 'Under $10')
         .when(F.col('fare_amount') < 25, '$10-25')
         .when(F.col('fare_amount') < 50, '$25-50')
         .when(F.col('fare_amount') < 100, '$50-100')
         .otherwise('$100+')) \
    .withColumn('distance_bucket',
        F.when(F.col('trip_distance') < 1, 'Under 1 mi')
         .when(F.col('trip_distance') < 3, '1-3 mi')
         .when(F.col('trip_distance') < 5, '3-5 mi')
         .when(F.col('trip_distance') < 10, '5-10 mi')
         .otherwise('10+ mi'))

print(f"  Added 15 computed columns")
print(f"  Total columns: {len(enriched_df.columns)}")


# ---- STEP 4.3: Filter unrealistic computed values ----
print("\nSTEP 4.3: Filtering unrealistic computed values...")

final_df = enriched_df.filter(
    (F.col('trip_duration_min') > 1) &
    (F.col('trip_duration_min') < 180) &
    ((F.col('speed_mph').isNull()) | (F.col('speed_mph') < 80))
)

final_count = final_df.count()
print(f"  After duration/speed filter: {final_count:,}")

# Cache for multiple downstream operations
final_df.cache()
print("  Data cached in memory!")


# ---- STEP 4.4: Post-transform quality validation ----
print("\nSTEP 4.4: Post-transform quality validation...")
print("QUALITY CHECKS:")

check_negative_fares = final_df.filter(F.col('fare_amount') < 0).count()
check_zero_distance = final_df.filter(F.col('trip_distance') <= 0).count()
check_null_duration = final_df.filter(F.col('trip_duration_min').isNull()).count()
check_future_dates = final_df.filter(F.year('tpep_pickup_datetime') != 2024).count()

print(f"  Negative fares:     {check_negative_fares} {'PASS' if check_negative_fares == 0 else 'FAIL'}")
print(f"  Zero distance:      {check_zero_distance} {'PASS' if check_zero_distance == 0 else 'FAIL'}")
print(f"  Null durations:     {check_null_duration} {'PASS' if check_null_duration == 0 else 'FAIL'}")
print(f"  Wrong year:         {check_future_dates} {'PASS' if check_future_dates == 0 else 'FAIL'}")

all_passed = (check_negative_fares + check_zero_distance + check_future_dates) == 0
print(f"\n  Overall: {'ALL CHECKS PASSED!' if all_passed else 'ISSUES FOUND!'}")

# Use only January data to fit in Colab memory
final_df = final_df.filter(F.col('pickup_month') == 1)
final_df.cache()
print(f"Filtered to January only: {final_df.count():,} rows")

print("\n" + "=" * 70)
print("PHASE 5: LOAD — Writing Organized Output")
print("=" * 70)

# ---- STEP 5.1: Write cleaned fact table (partitioned) ----
print("Writing fact table...")

final_df.write \
    .mode("overwrite") \
    .partitionBy("pickup_month") \
    .parquet("output/fact_trips")

print("  fact_trips/ written (partitioned by pickup_month)")

# ---- STEP 5.2: Create and write aggregated tables ----

# Daily summary
print("Writing daily summary...")
daily_agg = final_df.groupBy('pickup_date').agg(
    F.count('*').alias('total_trips'),
    F.round(F.sum('fare_amount'), 2).alias('total_fares'),
    F.round(F.sum('tip_amount'), 2).alias('total_tips'),
    F.round(F.sum('total_amount'), 2).alias('total_revenue'),
    F.round(F.avg('fare_amount'), 2).alias('avg_fare'),
    F.round(F.avg('trip_distance'), 2).alias('avg_distance'),
    F.round(F.avg('trip_duration_min'), 1).alias('avg_duration'),
    F.round(F.avg('tip_pct'), 1).alias('avg_tip_pct'),
    F.round(F.avg('speed_mph'), 1).alias('avg_speed'),
    F.sum(F.when(F.col('is_airport'), 1).otherwise(0)).alias('airport_trips'),
    F.sum(F.when(F.col('is_rush_hour'), 1).otherwise(0)).alias('rush_hour_trips')
)
daily_agg.write.mode("overwrite").parquet("output/agg_daily")
print("  agg_daily/ written")

# Hourly summary
print("Writing hourly summary...")
hourly_agg = final_df.groupBy('pickup_hour', 'time_of_day').agg(
    F.count('*').alias('trips'),
    F.round(F.avg('fare_amount'), 2).alias('avg_fare'),
    F.round(F.avg('trip_distance'), 2).alias('avg_distance'),
    F.round(F.avg('speed_mph'), 1).alias('avg_speed'),
    F.round(F.avg('tip_pct'), 1).alias('avg_tip_pct')
)
hourly_agg.write.mode("overwrite").parquet("output/agg_hourly")
print("  agg_hourly/ written")

# Zone summary (pickup locations)
print("Writing zone summary...")
zone_agg = final_df.groupBy('PULocationID').agg(
    F.count('*').alias('trips'),
    F.round(F.sum('total_amount'), 0).alias('total_revenue'),
    F.round(F.avg('fare_amount'), 2).alias('avg_fare'),
    F.round(F.avg('trip_distance'), 2).alias('avg_distance'),
    F.round(F.avg('tip_pct'), 1).alias('avg_tip_pct')
)
zone_agg.write.mode("overwrite").parquet("output/agg_zones")
print("  agg_zones/ written")

# Payment summary
print("Writing payment summary...")
payment_agg = final_df.groupBy('payment_name', 'pickup_month').agg(
    F.count('*').alias('trips'),
    F.round(F.sum('total_amount'), 0).alias('revenue'),
    F.round(F.avg('tip_pct'), 1).alias('avg_tip_pct')
)
payment_agg.write.mode("overwrite").parquet("output/agg_payment")
print("  agg_payment/ written")


# ---- STEP 5.3: Verify all outputs ----
print("\nVERIFYING OUTPUTS:")

outputs = {
    'fact_trips': 'output/fact_trips',
    'agg_daily': 'output/agg_daily',
    'agg_hourly': 'output/agg_hourly',
    'agg_zones': 'output/agg_zones',
    'agg_payment': 'output/agg_payment'
}

for name, path in outputs.items():
    df_check = spark.read.parquet(path)
    print(f"  {name:20s}: {df_check.count():>10,} rows x {len(df_check.columns)} cols")

print("\n" + "=" * 70)
print("PHASE 6: PIPELINE LOG")
print("=" * 70)

pipeline_log = {
    'pipeline_name': 'NYC_Taxi_ETL',
    'run_timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'status': 'SUCCESS' if all_passed else 'FAILED',
    'extract': {
        'source_files': files,
        'source_format': 'Parquet',
        'raw_rows': raw_count,
        'raw_columns': raw_columns
    },
    'transform': {
        'rows_after_cleaning': clean_count,
        'rows_removed_invalid': removed,
        'removal_pct': round(removed / raw_count * 100, 1),
        'rows_after_duration_filter': final_count,
        'columns_added': 15,
        'final_columns': len(final_df.columns),
        'quality_issues_found': {
            'negative_fares': int(negative_fares),
            'zero_distance': int(zero_distance),
            'zero_passengers': int(zero_passengers),
            'wrong_year': int(wrong_year)
        }
    },
    'load': {
        'fact_table': {'path': 'output/fact_trips', 'partition_by': 'pickup_month'},
        'aggregations': ['agg_daily', 'agg_hourly', 'agg_zones', 'agg_payment'],
        'output_format': 'Parquet'
    },
    'quality_checks': {
        'post_transform_negative_fares': int(check_negative_fares),
        'post_transform_zero_distance': int(check_zero_distance),
        'post_transform_wrong_year': int(check_future_dates),
        'all_passed': all_passed
    }
}

with open('etl_pipeline_log.json', 'w') as f:
    json.dump(pipeline_log, f, indent=2)

print("Pipeline log:")
print(json.dumps(pipeline_log, indent=2))

print("\n" + "=" * 70)
print("PHASE 7: DOWNSTREAM VALIDATION — Querying the Output")
print("=" * 70)

# Read from the OUTPUT (not the original data) — proves the pipeline works
fact = spark.read.parquet("output/fact_trips")
fact.createOrReplaceTempView("trips")

# Query 1: Monthly overview
print("MONTHLY OVERVIEW (from pipeline output):")
spark.sql("""
    SELECT pickup_month,
           COUNT(*) AS trips,
           ROUND(SUM(total_amount), 0) AS revenue,
           ROUND(AVG(fare_amount), 2) AS avg_fare,
           ROUND(AVG(trip_distance), 2) AS avg_distance,
           ROUND(AVG(tip_pct), 1) AS avg_tip_pct
    FROM trips
    GROUP BY pickup_month
    ORDER BY pickup_month
""").show()

# Query 2: Rush hour impact
print("RUSH HOUR vs NON-RUSH HOUR:")
spark.sql("""
    SELECT is_rush_hour,
           COUNT(*) AS trips,
           ROUND(AVG(fare_amount), 2) AS avg_fare,
           ROUND(AVG(trip_duration_min), 1) AS avg_duration,
           ROUND(AVG(speed_mph), 1) AS avg_speed
    FROM trips
    WHERE speed_mph IS NOT NULL
    GROUP BY is_rush_hour
""").show()

# Query 3: Airport vs non-airport
print("AIRPORT vs REGULAR TRIPS:")
spark.sql("""
    SELECT is_airport,
           COUNT(*) AS trips,
           ROUND(AVG(fare_amount), 2) AS avg_fare,
           ROUND(AVG(trip_distance), 2) AS avg_distance,
           ROUND(AVG(tip_pct), 1) AS avg_tip_pct
    FROM trips
    GROUP BY is_airport
""").show()

# Query 4: Fare bucket distribution
print("FARE BUCKET DISTRIBUTION:")
spark.sql("""
    SELECT fare_bucket,
           COUNT(*) AS trips,
           ROUND(SUM(total_amount), 0) AS total_revenue,
           ROUND(AVG(trip_distance), 2) AS avg_distance
    FROM trips
    GROUP BY fare_bucket
    ORDER BY CASE fare_bucket
        WHEN 'Under $10' THEN 1
        WHEN '$10-25' THEN 2
        WHEN '$25-50' THEN 3
        WHEN '$50-100' THEN 4
        ELSE 5 END
""").show()

# Query 5: Day of week pattern
print("DAY OF WEEK PATTERN:")
spark.sql("""
    SELECT day_name, pickup_day_of_week,
           COUNT(*) AS trips,
           ROUND(AVG(fare_amount), 2) AS avg_fare,
           ROUND(SUM(total_amount), 0) AS total_revenue
    FROM trips
    GROUP BY day_name, pickup_day_of_week
    ORDER BY pickup_day_of_week
""").show()

spark.stop()

print("\n" + "=" * 70)
print("     PROJECT 17 COMPLETE — PYSPARK ETL PIPELINE")
print("=" * 70)
print(f"""
ETL PIPELINE ON REAL NYC TAXI DATA:

  EXTRACT:
    - 3 Parquet files (Jan-Mar 2024 Yellow Taxi trips)
    - ~9M raw rows from NYC TLC official data

  TRANSFORM:
    - Data quality audit (nulls, negatives, wrong dates, zero values)
    - Removed {removed:,} invalid records ({removed/raw_count*100:.1f}%)
    - Added 15 computed columns (duration, speed, tip%, cost/mile,
      time categories, rush hour flag, airport flag, fare/distance buckets)
    - Post-transform validation (all quality checks passed)

  LOAD:
    - fact_trips: partitioned by pickup_month (clean trip data)
    - agg_daily: daily summary (trips, revenue, avg metrics)
    - agg_hourly: hourly patterns (speed, fare, tips by hour)
    - agg_zones: pickup zone performance (revenue, trips per zone)
    - agg_payment: payment method breakdown by month
    - Pipeline log: JSON metadata with row counts and quality results

  VALIDATE:
    - 5 downstream SQL queries on the output data
    - Monthly overview, rush hour impact, airport analysis,
      fare distribution, day-of-week patterns

PIPELINE BEST PRACTICES:
  1. Quality audit BEFORE cleaning (know what you're fixing)
  2. Quality validation AFTER cleaning (confirm it's fixed)
  3. Schema awareness (understand every column's meaning)
  4. Partitioned output (query efficiency)
  5. Pre-aggregated tables (dashboard-ready summaries)
  6. Pipeline logging (metadata for monitoring and debugging)
  7. Downstream validation (prove the output is usable)
""")
print("=" * 70)

